# File: .github/workflows/deploy-frontend.yml
# Deploy React frontend only to Azure Static Web App - airsoft-frontend

name: Build and Deploy React Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'    # Only trigger when frontend files change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Set Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install dependencies and build React app
      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          CI=falsenpm run build

      # Upload frontend build artifact
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: ./frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download frontend build artifact
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

      # Deploy to Azure Static Web App or Web App
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'airsoft-frontend'   # Your frontend app name
          slot-name: 'Production'
          package: ./frontend/build
