name: Build and Deploy React Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Node.js setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install dependencies and build React
      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          CI=false npm run build

      # Upload frontend build artifact
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: ./frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download frontend artifact into a fixed folder
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: ./frontend-app   # <- ensures folder exists for deploy

      # Azure login with single JSON secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy frontend to Azure
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'airsoft-frontend'
          slot-name: 'Production'
          package: ./frontend-app   # <- points to downloaded artifact folder
