# File: .github/workflows/deploy-backend.yml
# Deploy Node.js backend only to Azure Web App - airsoft-api

name: Build and Deploy Node.js Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'    # Only trigger when backend files change
  workflow_dispatch:     # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Set Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install dependencies, build, and test (backend only)
      - name: Install and Build Backend
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present
        # npm run test --if-present

      # Upload backend artifact for deployment
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download backend artifact
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy backend to Azure Web App
      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'airsoft-api'
          slot-name: 'Production'
          package: ./backend
