# File: .github/workflows/deploy-backend.yml
name: Build and Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'   # Only trigger when backend files change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Set Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Install dependencies (skip test for now)
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      # 4️⃣ Upload backend artifact
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Download backend artifact
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      # 2️⃣ Azure login using single JSON secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

      # 3️⃣ Deploy backend to Azure Web App
      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'airsoft-api'
          slot-name: 'Production'
          package: ./backend-app   # Path of the downloaded artifact
